// VBS 런처 스크립트: 커스텀 프로토콜 URL에서 id/pw를 파싱하여 IE 자동 로그인
const LAUNCHER_VBS = [
  "' ============================================================",
  "' Kyobo Scanner - IE Auto Login Launcher (최종 배포판)",
  "' ============================================================",
  "On Error Resume Next",
  "",
  "Dim url, id, pw, queryStr, params, i, kv",
  "Dim IE, Shell, Windows, win, targetIE, retry",
  "Dim doc, elID, elPW, elBtn",
  "",
  "If WScript.Arguments.Count > 0 Then url = WScript.Arguments(0)",
  "",
  "' 파라미터 파싱",
  'If InStr(url, "?") > 0 Then',
  '    queryStr = Mid(url, InStr(url, "?") + 1)',
  '    If Right(queryStr, 1) = "/" Then queryStr = Left(queryStr, Len(queryStr) - 1)',
  '    params = Split(queryStr, "&")',
  "    For i = 0 To UBound(params)",
  '        kv = Split(params(i), "=")',
  "        If UBound(kv) >= 1 Then",
  '            If LCase(kv(0)) = "id" Then id = kv(1)',
  '            If LCase(kv(0)) = "pw" Then pw = kv(1)',
  "        End If",
  "    Next",
  "End If",
  "",
  "' URL 디코딩 함수",
  "Function URLDecode(s)",
  "    Dim result, j",
  '    result = "" : j = 1',
  "    Do While j <= Len(s)",
  '        If Mid(s, j, 1) = "%" And j + 2 <= Len(s) Then',
  '            result = result & Chr(CInt("&H" & Mid(s, j + 1, 2)))',
  "            j = j + 3",
  '        ElseIf Mid(s, j, 1) = "+" Then',
  '            result = result & " " : j = j + 1',
  "        Else",
  "            result = result & Mid(s, j, 1) : j = j + 1",
  "        End If",
  "    Loop",
  "    URLDecode = result",
  "End Function",
  "",
  "id = URLDecode(id)",
  "pw = URLDecode(pw)",
  "",
  'If id = "" Or pw = "" Then WScript.Quit',
  "",
  "' 창 1회 생성 및 이동",
  'Set IE = CreateObject("InternetExplorer.Application")',
  "IE.Visible = True",
  'IE.Navigate "http://iscan.kyobobook.co.kr/kbb/intro"',
  "",
  "' IE 모드 전환 대기 (3초) 및 제어권 재연결",
  "WScript.Sleep 3000",
  'Set Shell = CreateObject("Shell.Application")',
  "Set targetIE = Nothing",
  "",
  "For retry = 1 To 15",
  "    Set Windows = Shell.Windows",
  "    For Each win In Windows",
  "        On Error Resume Next",
  '        If InStr(LCase(win.LocationURL), "iscan.kyobobook.co.kr") > 0 Then',
  "            Set targetIE = win",
  "            Exit For",
  "        End If",
  "        On Error GoTo 0",
  "    Next",
  "    If Not targetIE Is Nothing Then Exit For",
  "    WScript.Sleep 1000",
  "Next",
  "",
  "If targetIE Is Nothing Then WScript.Quit",
  "",
  "' 로딩 완료 대기",
  "Do While targetIE.Busy Or targetIE.ReadyState <> 4",
  "    WScript.Sleep 500",
  "Loop",
  "WScript.Sleep 1000",
  "",
  "' 값 입력 및 로그인",
  "Set doc = targetIE.Document",
  'Set elID = doc.getElementById("username")',
  'Set elPW = doc.getElementById("password")',
  'Set elBtn = doc.getElementById("authUser")',
  "",
  "If Not elID Is Nothing Then",
  "    elID.Value = id",
  "    elPW.Value = pw",
  "    elBtn.Click",
  "End If",
  "",
  "Set IE = Nothing",
  "Set targetIE = Nothing"
].join("\r\n");
